services:
  babycam:
    image: babycam:latest
    container_name: babycam
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
      - babycam_data:/app/snapshots   # Snapshots persistent
      - ./config.json:/app/config.json  # Config persistent
    environment:
      - TZ=Europe/Berlin
      - MQTT_BROKER=192.168.178.131
      - MQTT_PORT=1883
    extra_hosts:
      - "host.docker.internal:host-gateway"
    group_add:
      - "29"   # audio
      - "44"   # video

volumes:
  babycam_data:
